const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The only person you should try to be better than is the person you were yesterday. - Unknown",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "If you want to achieve greatness, stop asking for permission. - Anonymous",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The only source of knowledge is experience. - Albert Einstein",
    "The secret of getting ahead is getting started. - Mark Twain",
    "The harder I work, the luckier I get. - Samuel Goldwyn",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful. - Joshua J. Marine",
    "In three words I can sum up everything I've learned about life: It goes on. - Robert Frost",
    "Dream big and dare to fail. - Norman Vaughan",
    "The future starts today, not tomorrow. - Pope John Paul II",
    "The best revenge is massive success. - Frank Sinatra",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown Jr.",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "Don't count the days, make the days count. - Muhammad Ali",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. - Steve Jobs",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "Every strike brings me closer to the next home run. - Babe Ruth",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You have to be odd to be number one. - Dr. Seuss",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The secret of getting ahead is getting started. - Mark Twain",
    "The harder I work, the luckier I get. - Samuel Goldwyn",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful. - Joshua J. Marine",
    "Dream big and dare to fail. - Norman Vaughan",
    "The future starts today, not tomorrow. - Pope John Paul II",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown Jr.",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "Every strike brings me closer to the next home run. - Babe Ruth",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You have to be odd to be number one. - Dr. Seuss"
];
  
  
  
  
  let button = document.getElementById("btn")

  const getNewQuote = () => {
    let showQuotes = document.getElementById("showQuote").innerHTML = quotes[Math.floor(Math.random() * quotes.length)];
  }
